# Generated by Django 6.0.2 on 2026-02-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fasl', models.CharField(choices=[('Qishki', 'Qishki'), ('Yozgi', 'Yozgi'), ('Kuzgi', 'Kuzgi'), ('Bahorgi', 'Bahorgi')], max_length=20)),
                ('gender', models.CharField(choices=[('Erkaklar uchun', 'Erkaklar uchun'), ('Ayollar uchun', 'Ayollar uchun'), ('Bolalar uchun', 'Bolalar uchun')], max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
